ERROR - 2024-05-22 00:41:14 --> mysqli_sql_exception: Table 'users' already exists in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('CREATE TABLE `u...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Database/Migrations/2024-05-04-042902_AddUser.php(38): CodeIgniter\Database\Forge->createTable('users')
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(867): App\Database\Migrations\AddUser->up()
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Database/Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(338): CodeIgniter\CLI\Console->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2024-05-22 00:42:18 --> mysqli_sql_exception: Table 'users' already exists in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('CREATE TABLE `u...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Database/Migrations/2024-05-04-042902_AddUser.php(38): CodeIgniter\Database\Forge->createTable('users')
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(867): App\Database\Migrations\AddUser->up()
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Database/Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(338): CodeIgniter\CLI\Console->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2024-05-22 00:45:01 --> mysqli_sql_exception: Table 'users' already exists in /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(308): mysqli->query('CREATE TABLE `u...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/app/Database/Migrations/2024-05-04-042902_AddUser.php(38): CodeIgniter\Database\Forge->createTable('users')
#5 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(867): App\Database\Migrations\AddUser->up()
#6 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Database/MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Commands/Database/Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/CLI/Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(338): CodeIgniter\CLI\Console->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/vendor/codeigniter4/framework/system/Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 /Applications/XAMPP/xamppfiles/htdocs/SENA/api_ADMIRED/api_ADMIRED/spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
